require("prototypes.entity")
require("prototypes.item-subgroup")
require("prototypes.item")
require("prototypes.recipe-category")
require("prototypes.recipe")
require("prototypes.technology")

require("compatibility.atan-ash.data")
require("compatibility.space-age.data")
require("compatibility.any-planet-start.data")
